-- MySQL Script generated by MySQL Workbench
-- Thu Nov  8 13:35:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tms` DEFAULT CHARACTER SET utf8 ;
USE `tms` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tms`.`classes` ;

CREATE TABLE IF NOT EXISTS `tms`.`classes` (
  `crn` INT NOT NULL,
  `subject_code` VARCHAR(7) NOT NULL,
  `course_number` INT NOT NULL,
  `section` VARCHAR(7) NOT NULL,
  `credits` FLOAT NOT NULL,
  `title` VARCHAR(127) NOT NULL,
  `campus` VARCHAR(63),
  `instructors` VARCHAR(63),
  `instruction_type` VARCHAR(31) NOT NULL,
  `instruction_method` VARCHAR(31),
  `max_enroll` INT NOT NULL,
  `enroll` INT,
  `section_comments` VARCHAR(511),
  `building` VARCHAR(63),
  `room` VARCHAR(31),
  PRIMARY KEY (`crn`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`times` ;

CREATE TABLE IF NOT EXISTS `mydb`.`times` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `starttime` DATETIME NOT NULL,
  `endtime` DATETIME NOT NULL,
  `classcrn` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `classcrn_idx` (`classcrn` ASC) VISIBLE,
  CONSTRAINT `classcrn`
    FOREIGN KEY (`classcrn`)
    REFERENCES `mydb`.`classes` (`crn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
